create table SUPPLIERS (
  SUPPLIER_ID int,
  SUPPLIER_ADDRESS varchar(255),
  SUPPLIER_NAME varchar(255),
  PRIMARY KEY(SUPPLIER_ID)
);

create table CUSTOMERS (
  CUSTOMER_ID int,
  CUSTOMER_ADDRESS varchar(255),
  CUSTOMER_NAME varchar(255),
  CUSTOMER_MARGIN float,
  PRIMARY KEY(CUSTOMER_ID)
);

create table GOODS (
  GOOD_ID int,
  GOOD_NAME varchar(255),
  GOOD_PRICE int,
  PRIMARY KEY(GOOD_ID)
);

create table GOODS_SUPPLING (
  GOOD_SUPPLING_ID int,
  GOOD_ID int,
  GOOD_SUPPLING_BEST_BEFORE date,
  GOOD_SUPPLING_QUANTITY int,
  GOOD_SUPPLING_PRICE int,
  SUPPLIER_ID int,

  PRIMARY KEY(GOOD_SUPPLING_ID),
  FOREIGN KEY(GOOD_ID) REFERENCES GOODS(GOOD_ID) ON DELETE CASCADE,
  FOREIGN KEY(SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID) ON DELETE CASCADE
);

create table GOODS_CUSTOMING (
  GOOD_CUSTOMING_ID int,
  GOOD_SUPPLING_ID int,
  GOOD_CUSTOMING_QUANTITY int,
  GOOD_CUSTOMING_MARGIN float,
  GOOD_CUSTOMER_ID int,
  GOOD_CUSTOMING_DATE date,

  PRIMARY KEY(GOOD_CUSTOMING_ID),
  FOREIGN KEY(GOOD_SUPPLING_ID) REFERENCES GOODS_SUPPLING(GOOD_SUPPLING_ID) ON DELETE CASCADE,
  FOREIGN KEY(GOOD_CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID) ON DELETE CASCADE
);