-- No context.

grant select on BANK_ACCOUNTS to BANK_CLIENT_USER;

CREATE OR REPLACE FUNCTION BONDARENKO.MY_SECURITY_FUNCTION
(P_SCHEMA IN VARCHAR2, P_OBJECT IN VARCHAR2)
RETURN VARCHAR2
    AS
    BEGIN
        IF (USER = P_SCHEMA) THEN
    RETURN ' ';
        ELSE
    RETURN '(SELECT USER_ID FROM USER_TO_USER_MAPPING WHERE USER_NAME = USER) = ACC_USER_ID';
       END IF;
   END;
   
BEGIN
  DBMS_RLS.ADD_POLICY
   (OBJECT_SCHEMA   => 'BONDARENKO',
    OBJECT_NAME     => 'BANK_ACCOUNTS', 
    POLICY_NAME     => 'BANK_ACCOUNT_ACCESS_POLICY',
    FUNCTION_SCHEMA => 'BONDARENKO',
    POLICY_FUNCTION => 'MY_SECURITY_FUNCTION',
    STATEMENT_TYPES => 'SELECT, INSERT, UPDATE, DELETE',
    UPDATE_CHECK    => TRUE,
    ENABLE  => TRUE);
  END;
  
BU> select * from BONDARENKO.BANK_Accounts;

-- With context:
TODO
