audit user;
audit session;
audit system;

SELECT NAME, VALUE FROM SYS.V_$PARAMETER WHERE NAME LIKE 'AUD%';
SELECT TABLE_NAME FROM DICTIONARY WHERE TABLE_NAME LIKE '%AUD%';


SELECT * FROM SYS.DBA_AUDIT_EXISTS;

GRANT AUDIT SYSTEM TO KOSTYUCHENKO;



-- Изменения паролей

SELECT *
FROM SYS.DBA_AUDIT_OBJECT
WHERE ACTION_NAME='GRANT PRIVELEGE'
ORDER BY EXTENDED_TIMESTAMP desc;

-- Доступ несуществующих пользователей

CREATE USER KOSTYUCHENKO5 IDENTIFIED BY mnbvcxz;
GRANT CREATE SESSION TO KOSTYUCHENKO5;
DROP USER KOSTYUCHENKO5;

SELECT *
FROM SYS.DBA_AUDIT_TRAIL
WHERE ACTION_NAME='LOGON'
  AND EXTENDED_TIMESTAMP > TIMESTAMP '2015-12-28 08:00:00'
  AND EXTENDED_TIMESTAMP < TIMESTAMP '2015-12-28 12:45:00'
  AND NOT EXISTS (
    SELECT * FROM SYS.DBA_USERS
    WHERE SYS.DBA_AUDIT_TRAIL.USERNAME = SYS.DBA_USERS.USERNAME
  )
ORDER BY EXTENDED_TIMESTAMP desc;


BEGIN
  DBMS_FGA.ADD_POLICY(
    object_schema=>'KOSTYUCHENKO',
    object_name=>'GOODS',
    policy_name=>'GOODS_SELECT');
    
  DBMS_FGA.ADD_POLICY(
    object_schema=>'KOSTYUCHENKO',
    object_name=>'GOODS',
    policy_name=>'GOODS_DELETE',
    statement_types=>'DELETE');
END;


-- Исчезновение записей

SELECT * FROM GOODS;
DELETE FROM GOODS WHERE GOOD_ID=61;

SELECT *
FROM SYS.DBA_FGA_AUDIT_TRAIL
WHERE POLICY_NAME = 'GOODS_DELETE';



-- Обращения к таблице

SELECT COUNT(*)
FROM SYS.DBA_FGA_AUDIT_TRAIL
WHERE POLICY_NAME = 'GOODS_SELECT';